import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import styles from './demo.module.css';

export default function DemoPage() {
  return (
    <Layout title="90-Second Demo" description="Quick demo of the Physical AI & Humanoid Robotics textbook">
      <div className={styles.demoContainer}>
        <div className={styles.header}>
          <h1>90-Second Demo</h1>
          <p>Experience the key features of our Physical AI & Humanoid Robotics Interactive Textbook</p>
        </div>

        <div className={styles.demoSteps}>
          <div className={styles.step}>
            <div className={styles.stepNumber}>1</div>
            <div className={styles.stepContent}>
              <h3>Browse the Textbook</h3>
              <p>Explore 6-8 chapters on Physical AI and Humanoid Robotics concepts.</p>
              <Link to="/docs/introduction" className={styles.demoButton}>
                Browse Textbook
              </Link>
            </div>
          </div>

          <div className={styles.step}>
            <div className={styles.stepNumber}>2</div>
            <div className={styles.stepContent}>
              <h3>Ask the AI Assistant</h3>
              <p>Get answers to your questions based only on textbook content using our RAG-powered chatbot.</p>
              <Link to="/chat" className={styles.demoButton}>
                Chat with AI
              </Link>
            </div>
          </div>

          <div className={styles.step}>
            <div className={styles.stepNumber}>3</div>
            <div className={styles.stepContent}>
              <h3>Personalize Your Experience</h3>
              <p>Adjust content complexity based on your background and expertise level.</p>
              <Link to="/dashboard" className={styles.demoButton}>
                Personalize
              </Link>
            </div>
          </div>

          <div className={styles.step}>
            <div className={styles.stepNumber}>4</div>
            <div className={styles.stepContent}>
              <h3>Translate to Urdu</h3>
              <p>Access content in Urdu with one-click translation while preserving formatting.</p>
              <Link to="/docs/introduction" className={styles.demoButton}>
                Try Translation
              </Link>
            </div>
          </div>

          <div className={styles.step}>
            <div className={styles.stepNumber}>5</div>
            <div className={styles.stepContent}>
              <h3>Test Auto-Generated Content</h3>
              <p>Access summaries, quizzes, and personalized explanations generated by our AI agents.</p>
              <Link to="/dashboard" className={styles.demoButton}>
                View AI Content
              </Link>
            </div>
          </div>
        </div>

        <div className={styles.demoFeatures}>
          <h2>Key Features Demonstrated</h2>
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <h3>📚 Education-First Design</h3>
              <p>Readable in under 45 minutes with short, focused chapters</p>
            </div>
            <div className={styles.featureCard}>
              <h3>🤖 AI-Native Integration</h3>
              <p>RAG-powered chatbot with textbook-only responses</p>
            </div>
            <div className={styles.featureCard}>
              <h3>🌍 Accessibility & Localization</h3>
              <p>One-click Urdu translation with preserved formatting</p>
            </div>
            <div className={styles.featureCard}>
              <h3>🏗️ Clean Architecture</h3>
              <p>Modular design with Docusaurus frontend and FastAPI backend</p>
            </div>
            <div className={styles.featureCard}>
              <h3>⚡ Resource Efficiency</h3>
              <p>Optimized for free-tier deployment with fast loading</p>
            </div>
            <div className={styles.featureCard}>
              <h3>👥 User Experience Priority</h3>
              <p>Smooth reading experience with personalization options</p>
            </div>
          </div>
        </div>

        <div className={styles.gettingStarted}>
          <h2>Getting Started</h2>
          <p>To run the application locally:</p>
          <div className={styles.codeBlock}>
            <pre>{`# Backend
cd backend
pip install -r requirements.txt
uvicorn rag.app.main:app --reload

# Frontend
cd frontend
npm install
npm start`}</pre>
          </div>
          <p>For a complete demo experience, make sure to set up your OpenAI API key and Qdrant configuration.</p>
        </div>
      </div>
    </Layout>
  );
}